disabled_rules:
  - trailing_whitespace
  - type_name
  - line_length
  - identifier_name
  - large_tuple
  - function_body_length
  - function_parameter_count
  - unused_closure_parameter


opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_string
  - fatal_error_message
  - legacy_random
  - let_var_whitespace
  - yoda_condition

included:

excluded:
  - Carthage
  - Pods
  - R.generated.swift

force_cast: warning

force_try:
  severity: warning

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 1000
  error: 1200

vertical_whitespace:
  max_empty_lines: 2

cyclomatic_complexity:
  warning: 20
  error: 30

reporter: "xcode"
